version: '3.5'

services:
    universi-me:
        container_name: universi-me
        build:
            context: .
        restart: unless-stopped
        networks:
            - universi-me-network
        ports:
            - "8080:8080"
        volumes:
            - universi-me-login-session:/var/lib/login-sesion/data
        depends_on:
            - universi-me-db
            - universi-me-mongo
        environment:
            API_DB_URL: jdbc:postgresql://universi-me-db:5432/${API_DB_NAME}
            API_DB_MONGO_URI: mongodb://universi-me-mongo:27017/
        env_file:
            - .env

    universi-me-db:
        container_name: universi-me-postgres
        image: postgres:latest
        restart: unless-stopped
        networks:
            - universi-me-network
        ports:
            - "5432:5432"
        volumes:
            - universi-me-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${API_DB_USER}
            POSTGRES_PASSWORD: ${API_DB_PASS}
            POSTGRES_DB: ${API_DB_NAME}
            PGDATA: /var/lib/postgresql/data
        env_file:
            - .env

    universi-me-mongo:
        container_name: universi-me-mongo
        image: mongo:latest
        restart: unless-stopped
        networks:
            - universi-me-network
        ports:
            - "27017:27017"
        volumes:
            - universi-me-mongo-data:/data/db
        env_file:
            - .env

    universi-me-pgadmin:
        container_name: universi-me-pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_PATH_PREFIX: /pgadmin4
            SCRIPT_NAME: /pgadmin4
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: ${API_DB_PASS}
        env_file:
            - .env
        ports:
            - "16543:80"
        depends_on:
            - universi-me-db
        volumes:
            - universi-me-pgadmin-data:/var/lib/pgadmin
        networks:
            - universi-me-network

volumes:
    universi-me-pgadmin-data:
        driver: local
    universi-me-postgres:
        driver: local
    universi-me-login-session:
        driver: local
    universi-me-mongo-data:
        driver: local

networks:
    universi-me-network:
        driver: bridge