CREATE TABLE competence_type
(
    id_competence_type INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    CONSTRAINT pk_competence_type PRIMARY KEY (id_competence_type)
);

ALTER TABLE competence_type
    ADD CONSTRAINT uc_competence_type_name UNIQUE (name);