spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  web:
    resources:
      cache:
        period: 3600

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# SERVER
server:
  port: 8080
  servlet:
    session:
      timeout: 43200
      persistent: false
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB


# SPRINGDOC
springdoc:
  version: 1.0

# GOOGLE API AUTH
GOOGLE_CLIENT_ID: 110833050076-ib680ela4hfqr2c0lhc9h19snrsvltnd.apps.googleusercontent.com

# IMAGEM CONFIG
SALVAR_IMAGEM_EM_DISCO: false
DIRETORIO_DA_IMAGEM: src/main/resources/static/img/imagem/

# IMGUR API CLIENT-ID
IMGUR_CLIENT_ID: e4f58fc81daec99

# LOGIN CONFIG
REGISTRAR_SE_ATIVADO: false

# TEST Profile
---
spring:
  config:
    activate:
      on-profile: test
  # Flyway
  flyway:
    enabled: false

  datasource:
    url: jdbc:h2:~/h2/universi-api;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


# DEV Profile
---
spring:
  config:
    activate:
      on-profile: dev

  # POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5434/universime
    username: postgres
    password: postgres
  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5434/universime
    user: postgres
    password: postgres
  # H2 Console
  h2:
    console:
      enabled: false


# PROD Profile
---
spring:
  config:
    activate:
      on-profile: prod

  # POSTGRES
  datasource:
    url: jdbc:postgresql://localhost:5434/universime
    username: postgres
    password: postgres
  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5434/universime
    user: postgres
    password: postgres
  # H2 Console
  h2:
    console:
      enabled: false